{% set name = "desdeo-vis" %}
{% set version = "0.2.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4fe3db61ca84742f0384e3d4fd9755a50d1cec701e7a2fb1b91910406505e52c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.6
    - ipywidgets >=7.0.0
    - widgetsnbextension
  run:
    - python >=3.6
    - ipywidgets >=7.0.0
    - widgetsnbextension
    - desdeo >=0.1.3
    - matplotlib
    - altair
    - vega

test:
  imports:
    - desdeo_vis
    - desdeo_vis.nbextension
    - desdeo_vis.plot
    - desdeo_vis.widget

about:
  home: https://github.com/industrial-optimization-group/desdeo-vis
  license: MPL-2.0
  license_file: 'LICENSE'
  summary: |
    Visualisations and preference selection widgets for the DESDEO interactive
    multiobjective optimization library
  description: |
    DESDEO is a free and open source Python-based framework for developing and
    experimenting with interactive multiobjective optimization. This package
    provides plotting functions and preferences selection widgets to be used
    with Jupyter notebook.
  doc_url: 'https://desdeo.readthedocs.io/projects/desdeo-vis/'
  dev_url: 'https://github.com/industrial-optimization-group/desdeo-vis'

extra:
  recipe-maintainers:
    - frankier
