travis:
  secure:
    BINSTAR_TOKEN: oeNlvlwzCnBTPARLCLzBTc5Sv1Wxg+QxMC7RFzqPPZ9tWZoEgcKjgmpTEPw/uM9VPQsZngm5pIjQ8suW9qDAsr6f7nz+aXUPGyEQB9G42X3Zt3b49SkwZFHoe3YDjqiQAXcQK3uPxKS2GyRkZiAXTTNXpMIx4eO5pufmDd3yoN601G48itd+vzSpXdMXjrBq2CzO39PYy1Vuehjs9TgJMqZfIrJiYPBME1rNEeoS91ndH8n0pt/z1P2iu3d/sfkxSXY72iCqzYduKK4A6MvixSoXVQBAQ59+/7+ZYsESmZ88OulNHIlZ6JTF/Mppgegfw5wTq4MHSrVtAjnDJjt+BpK4qdVO1MVHb5V+2CI+kJtk1tSq7ksVKANdaUj4KVwMEtaKICEHUJ/e6lm4UXxvBQsEz0UPGLHe8h6/KCWcH8+nJdA5GU4FpT/7zysA7rUT9Q28+3y0nXRUxNmSzxqDGGzfXWZwq1kAF0HVQxFxiyWMhrdBjI+oUcsI2oKFW9CmXi/IH1O1cUjXPXeuURIIbJ3mrCffjI0eGourJTK+jbDjyZWLvG0xnoSCqg8KVI7mMFBmdbwlV/KG7WKAIj9ld9FXEpcEXf+zUpA1bQNDPOQkw93r4ARQZNNQsnTaUwLgOVnwuRwYGtv9OZr4MmPqiWdhRdyEbWIKsseQHBKtpmE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
