travis:
  secure:
    BINSTAR_TOKEN: QzVEfkXcWvC3gDfYCLzdoNPd2VRALH466Oe/MvwHmANfNYOljSGXsvK1cCBVnLfEpIo07m1Fmhbbs70GdEnRJVordNNztjL9y4m7UAUnJZUPU9BPDrpdnZkXk4wUOIih1gM/oNZmi+xmfAhE0zwUBYbfAfulg/Wqlu04vb61OFsuKpcbVeEqjiFsag7B0Uw5FFvVbeKbp7Y9fPn6dZmhBOl6FYhh0iGs4VgNNzydEVxg7tO1ITS3G4yLpc03FEFLUSH70N+1WaIScqMR02qfmmEKoggxa639m/d9NT958YTJSJfsWYc393GbS+U5x5gVNN3YqyMnV4W+tFzZnTr3YoVszFxlKE1fMmUpJh3ey7by4/yRgbKfjKVQr7nRrWHnR9CSwX1lFFLC3VCK65yV2NYE2ovClAWf2tJlHpf6hEAIFalkpnwdZ0+d3ug+AXPDkTUfw2wf1kDIT7j2JQZvtdmuhUIIgEQ4HDaTLTg8Zj9Xe+sm7YiipwvfWC4jqJTLYRemoADDeOUA27yZcaCzdosMkwSZ/fnS7ovA4MnvtiKMhMmsDsI16kIK+PwER3oPhiKm9i6ERCXEiYG/Cw1nrqKRMV751ECYSHWzMGmtarXelr4p4bQxt42SSWEqAyhuEPQKVjCZrL037BDqPmnov0z6snYfZRBMc8KlNSQPj0o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
