travis:
  secure:
    BINSTAR_TOKEN: ttPBUIqUfDKO7Y5Gj4PqZtmqLgHpfgflRqPUJek1iQJeDmu3m8ZoO0XEErHogIUSY/eXJ5Sryndw32ufkaWDazbYcpL02SWxv2w7MHNGDSujFrqDAmaqAPcJzHAq+U+rcP8d77UpcHTDdgn6epMxCyXpt0+WqyQK9Zr8vxPVxY2TCO7JZ5aCVfU7aL0qR373dKmB0tyw4atTySlI8B10KVEAV7BkW8zgjtfDR45h/mueD2QDfZSARFQVhQ996ARIpBwskB+fE5SWxTrtkovUdFO/6yYHRQZfSuvMkNLbVcvFWcEnnWWLIkYtxHSuUk85bgTmWmhRQdhabI3veipzB3CTA+Uwst7qcMI0vm5dJcFiz8GB3v3pBkZjaoB9IF7C0q3dNHOPrqinrta+95S3WI3/ouBiuMAdrSZQCydUrtAn/Mr+s+zwSy2edCl2TilMDLgmJuEqsPwZBPPQ7myPSJURQFAlK50ncgBlZyV9LeVsxfC94/j/zO/avwKMjDfQy7WT5CjTy0uaQVzqZeYjhxC48Jb1J8c7g4SQmDPb87IpZCqrv8SB+QqIV1zxEx2zlK1Bu4OUUQlcYVhIXjssyUgvT719eSuqf9MYTyAWyPqCg8VPgoI9mR50+9p69ZPf/APnTidH6jWd43YTY1uCpJsYHp5DdzyMSletDJUgtnQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
